# Generated by Django 6.0.7 on 2026-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('q1', models.CharField(max_length=20)),
                ('q2', models.CharField(max_length=20)),
                ('q3', models.CharField(max_length=20)),
                ('q4', models.CharField(max_length=20)),
                ('q5', models.CharField(max_length=20)),
                ('q6', models.CharField(max_length=20)),
                ('q7', models.CharField(max_length=20)),
                ('q8', models.CharField(max_length=20)),
                ('q9', models.CharField(max_length=20)),
                ('q10', models.CharField(max_length=20)),
                ('overall_rating', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], default='Good', max_length=20)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('addressed', 'Addressed')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
