# Generated by Django 4.2.21 on 2026-07-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
    ]
